### ISSUE TITLE
Error with mongoseed

### ISSUE THREAD

**Issue by sundayz-hunter** [koenbuyens/Damn-Vulnerable-OAuth-2.0-Applications#7]
Hi, 
I have a problem with mongo db.
Here my result when i launch docker-compose up : 

` % docker-compose up           
Recreating mongodb                      ... done
Starting insecureapplication_selenium_1 ... done
Recreating mongoseed                    ... done
Recreating gallery                      ... done
Recreating photoprint                   ... done
Recreating attacker                     ... done
Attaching to mongodb, insecureapplication_selenium_1, mongoseed, gallery, photoprint, attacker
gallery       | 
gallery       | > gallery@1.1.0 start /usr/src/app
gallery       | > node app.js
gallery       | 
selenium_1    | 2022-10-31 18:23:42,553 INFO Included extra file "/etc/supervisor/conf.d/selenium-debug.conf" during parsing
selenium_1    | 2022-10-31 18:23:42,559 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
selenium_1    | 2022-10-31 18:23:42,563 INFO supervisord started with pid 7
selenium_1    | 2022-10-31 18:23:43,573 INFO spawned: 'xvfb' with pid 9
selenium_1    | 2022-10-31 18:23:43,576 INFO spawned: 'fluxbox' with pid 10
selenium_1    | 2022-10-31 18:23:43,615 INFO spawned: 'vnc' with pid 11
selenium_1    | 2022-10-31 18:23:43,716 INFO spawned: 'selenium-standalone' with pid 13
selenium_1    | 2022-10-31 18:23:44,125 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 2022-10-31 18:23:44,125 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 2022-10-31 18:23:44,125 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 2022-10-31 18:23:44,126 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 18:23:45.760 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
selenium_1    | 18:23:46.342 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
selenium_1    | 2022-10-31 18:23:46.578:INFO::main: Logging initialized @2624ms to org.seleniumhq.jetty9.util.log.StdErrLog
mongodb       | 
mongodb       | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
mongodb       |   see https://jira.mongodb.org/browse/SERVER-54407
mongodb       |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
mongodb       |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
mongodb       | 
mongodb exited with code 132
mongoseed     |                                                                                                      
mongoseed     | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
mongoseed     |   see https://jira.mongodb.org/browse/SERVER-54407
mongoseed     |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
mongoseed     |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
mongoseed     | 
photoprint    | 
photoprint    | > photoprint@1.0.0 start /usr/src/app
photoprint    | > node app.js
photoprint    | 
photoprint    | Printing Application listening on http://localhost:3000
attacker      | 
attacker      | > attacker@1.0.0 start /usr/src/app
attacker      | > node app.js
attacker      | 
selenium_1    | 18:23:47.797 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
gallery       | Gallery Application listening on :::3005
gallery       | (node:17) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo EAI_AGAIN mongodb:27017]
gallery       |     at Pool.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/topologies/server.js:564:11)
gallery       |     at emitOne (events.js:116:13)
gallery       |     at Pool.emit (events.js:211:7)
gallery       |     at Connection.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:317:12)
gallery       |     at Object.onceWrapper (events.js:317:30)
gallery       |     at emitTwo (events.js:126:13)
gallery       |     at Connection.emit (events.js:214:7)
gallery       |     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:246:50)
gallery       |     at Object.onceWrapper (events.js:315:30)
gallery       |     at emitOne (events.js:116:13)
gallery       |     at Socket.emit (events.js:211:7)
gallery       |     at emitErrorNT (internal/streams/destroy.js:73:8)
gallery       |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
gallery       |     at process._tickCallback (internal/process/next_tick.js:181:9)
gallery       | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
gallery       | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
selenium_1    | 18:23:48.093 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
attacker      | Attacker Application listening on :::1337
mongoseed     | 2022-10-31T18:24:12.950+0000    error connecting to host: could not connect to server: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: mongodb:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup mongodb: Temporary failure in name resolution }, ] }
mongoseed exited with code 1
`

**Comment by Gundwane21** [comment]
I experienced the same error. The problem is docker-compose.yaml command
mongodb — smallfiles —logpath=/dev/null

—smallfiles flag is deprecated in mongodb

you need to remove that flag. Just Change line 20 in /insecureapplication/docker-compose.yml without the —smallfiles flag
